### ISSUE TITLE
Integrate with Spark

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#1295]
More reading at https://github.com/opensearch-project/sql/issues/1116

### Goal
* Setup the solution for end to end production use case verification.
* Test the performance.
* Understand how to size the Spark cluster.
* Understand cost model.

### Tasks
- [ ] Setup Spark docker cluster
    - [ ] Thrfit JDBC Server
    - [ ] LDAP
- [ ] Add Spark data source in OpenSearch SQL.
- [ ] Add OpenSearch Spark connector in Spark.
- [ ] Create the derived data set creating streaming query in Spark. 
- [ ] OpenSearch Docker Compose.

### Goal
* OpenSearch 2.x release.
* We will introduce the ability to create materialized views on data stored in object stores like S3. 

### Tasks
- [ ] Add low level derived dataset creation API. The following derived dataset should be supported
    - [ ] Materialized view
    - [ ] Covering index
    - [ ] Skipping Index
- [ ] Add high level streaming query syntax- optional
