### ISSUE TITLE
Performance test on large dataset

### ISSUE THREAD

**Issue by ps48** [opensearch-project/sql#1399]

**Comment by seankao-az** [comment]
## Tasks

- [ ] Create end to end Spark+OpenSearch setup with Locust and Grafana
- [ ] Decide what large dataset to use
- [ ] Decide what metrics to use for benchmarking
- [ ] Write the queries
- [ ] Run benchmarking for baseline direct queries
- [ ] Create skipping index & materialized view
- [ ] Run benchmarking for accelerated queries

**Comment by qianheng-aws** [comment]
Parking: Low activity and deprioritized during triage. Labeled `triage/parked` for tracking. Reopen if needed.
