### ISSUE TITLE
[FEATURE] Implement pagination in V2

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/sql#1759]
This ticket supersedes #656 and tracks implementation progress:
- [x] - Pagination basement - support `select * from <table>` #1666
- [x] - Support `WHERE` clause - #1500 
- [x] - Support `ORDER BY` clause - #1599
- [ ] - Support `LIMIT` clause - WIP:
  - [ ] - Design review #1752
- [ ] - Support system queries - tracked by #1712 
- [ ] - Support `OFFEST` clause
- [ ] - Support aggregation and `GROUP BY` clause
- [ ] - Support `NESTED` function - tracked by #1718
- [ ] - Support pagination in PPL
- [ ] - Support query parameters with pagination

Other related issues:
- [ ] - #947
- [ ] - #78
- [ ] - #656

Issues from the list above could be auto-closed once all listed features are implemented.
