### ISSUE TITLE
Support match_phrase function in SQL/PPL query engine

### ISSUE THREAD

**Issue by chloe-zh** [opensearch-project/sql#185]
Related design is presented in issue #182 

### Todo list
- [ ] Support the `match_phrase` functionality by pushing it down to the search engine
- [ ] Enable `match_phrase` function in SQL and PPL syntax and parser, including all the available parameters
- [ ] Make sure the function in new engine is compatible with the old engine support (including `match_phrase` and `matchphrase` functions in old engine)
- [ ] Add unit tests. (Unit tests are mandatory for all code changes.)
- [ ] Add integration test cases for `match_phrase`
- [ ] Update user manual

### Function details

The `match_phrase` function maps to the match phrase query used in search engine. This query analyzes the text and creates a phrase query out of the analyzed text.

**Syntax:**
 `match_phrase(field_expression, query_expression[, option=<option_value>]*)`

**Available options:**

* analyzer
* zero_terms_query

**Sample queries:**

```
# Search query 1
GET my_index/_search
{
  "query": {
    "match_phrase": {
      "message": "this is a test"
    }
  }
}

# SQL
SELECT * FROM my_index WHERE match_phrase(message, "this is a test")

# PPL 
source=my_index | match type=match_phrase field=message query="this is a test"


# Search query 2
GET my_index/_search
{
  "query": {
    "match_phrase": {
      "message": {
        "query": "this is a test",
        "analyzer": "my_analyzer"
      }
    }
  }
}

# SQL
SELECT* FROM my_index WHERE match_phrase(message, "this is a test", analyzer="my_analyzer") 

# PPL 
source=my_index | where match_phrase(message, "this is a test", analyzer="my_analyzer")
```

**Comment by MaxKsyunz** [comment]
@penghuo, should the PPL parser support alternative spelling of `match_phrase` like `matchphrase`? 

For example, are queries like `source=index | where matchphrase(field, 'text')` valid?

**Comment by joshuali925** [comment]
@MaxKsyunz `match_pharse` should be enough, i don't think PPL functions support alternative spellings (there is `date_format()` but not `dateformat()`)

**Comment by MaxKsyunz** [comment]
@joshuali925, here's a demo of the changes in PR #604
 
https://user-images.githubusercontent.com/99687200/168006197-8599dc17-3cf0-4e8c-92aa-a6b82a04081b.mp4

**Comment by acarbonetto** [comment]
fixed by: https://github.com/opensearch-project/sql/pull/604
