### ISSUE TITLE
Support match_phrase_prefix function in SQL/PPL query engine

### ISSUE THREAD

**Issue by chloe-zh** [opensearch-project/sql#186]
Related design is presented in issue #182 

### Todo list
- [ ] Support the `match_phrase_prefix` functionality by pushing it down to the search engine
- [ ] Enable `match_phrase_prefix` function in SQL and PPL syntax and parser, including all the available parameters
- [ ] Add unit tests. (Unit tests are mandatory for all code changes.)
- [ ] Add integration test cases for `match_phrase_prefix`
- [ ] Update user manual

### Function details

The `match_phrase_prefix` function maps to the match phrase prefix query used in search engine. This query returns documents that contains the words of a provided text, in the same order as provided. The last term of the provided text is treated as a prefix, matching any words that begin with that term.

**Syntax:**
 `match_phrase_prefix(field_expression, query_expression[, option=<option_value>]*)`

**Available options:**

* analyzer
* max_expansions
* slop
* zero_terms_query

**Sample queries:**

```
# Search query
GET my_index/_search
{
  "query": {
    "match_phrase_prefix": {
      "message": {
        "query": "quick brown f"
      }
    }
  }
}

# SQL
SELECT * FROM my_index WHERE match_phrase_prefix(message, "quick brown f")

# PPL
source=my_index | where match_phrase_prefix(message, "quick brown f")
```

**Comment by acarbonetto** [comment]
fixed by https://github.com/opensearch-project/sql/pull/661 and https://github.com/Bit-Quill/opensearch-project-sql/pull/79
