### ISSUE TITLE
Support combined_fields function in SQL/PPL query engine

### ISSUE THREAD

**Issue by chloe-zh** [opensearch-project/sql#189]
Related design is presented in issue #182 

### Todo list
- [ ] Support the `combined_fields` functionality by pushing it down to the search engine
- [ ] Enable `combined_fields` function in SQL and PPL syntax and parser, including all the available parameters
- [ ] Add unit tests. (Unit tests are mandatory for all code changes.)
- [ ] Add integration test cases for `combined_fields`
- [ ] Update user manual

### Function details

The `combined_fields` function maps to the combined fields query used in the search engine. This query supports searching multiple text fields as if their contents had been indexed into one combined field.

**Syntax:**
`combined_fields([field_list], query_expression[, option=<option_value>]*)`

**Available options:**
- analyzer
- auto_generate_synonyms_phrase_query
- operator
- minimum_should_match
- zero_terms_query

**Sample query:**
```
# Search query
GET my_index/_search
{
  "query": {
    "combined_fields" : {
      "query":      "database systems",
      "fields":     [ "title", "abstract", "body"],
      "operator":   "and"
    }
  }
}

# SQL
SELECT * FROM my_index WHERE combined_fields([title, abstract, body], "database systems", operator=and)

# PPL
source=my_index | where combined_fields([title, abstract, body], "database systems", operator=and)
```

**Comment by joshuali925** [comment]
@penghuo OpenSearch doesn't support `combined_fields`, should we close this or open an upstream feature request?

**Comment by Yury-Fridlyand** [comment]
@SViradiya-MarutiTech, thank you for your feedback. `combined_fields` query should be implemented first in the OpenSearch itself. You are welcome to open a Feature Request in the [main repo](https://github.com/opensearch-project/OpenSearch/issues?q=is%3Aissue+is%3Aopen+combined_fields) and describe your needs.

**Comment by SViradiya-MarutiTech** [comment]
@Yury-Fridlyand  added [#3996](https://github.com/opensearch-project/OpenSearch/issues/3996)

**Comment by dai-chen** [comment]
Closing this for now. We can work on this once OpenSearch adds the support. Thanks!
