### ISSUE TITLE
[FEATURE] Support date and time functions

### ISSUE THREAD

**Issue by Yury-Fridlyand** [opensearch-project/sql#722]
Copied from https://github.com/opendistro-for-elasticsearch/sql/issues/709.

Implementation should match MySQL standard: https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html

- [x] date - #991
- [x] time
- [x] timestamp
- [x] adddate
- [x] date_add
- [x] date_format
- [x] date_sub
- [x] dayname
- [x] dayofweek
- [x] dayofmonth
- [x] dayofyear
- [x] from_days
- [x] makedate - #755
- [x] maketime- #755
- [x] monthname
- [x] hour
- [x] minute
- [x] second
- [x] microsecond
- [x] day
- [x] week
- [x] month
- [x] quarter
- [x] year
- [x] subdate
- [x] time_to_sec
- [x] to_days
- [x] addtime - #1194
- [x] adddate (update) - #1182
- [x] convert_tz - #848
- [x] curdate - #754
- [x] current_date - #754
- [x] current_time - #754
- [x] current_timestamp - #754
- [x] curtime - #754
- [x] datediff - #1195
- [x] datetime - #848
- [x] date_add (update) - #1182
- [x] date_sub (update) - #1182
- [x] day_of_month - #1227
- [x] day_of_week - #1228
- [x] day_of_year - #1128
- [x] extract - #1421
- [x] hour_of_day - #1226
- [x] from_unixtime - #835
- [x] get_format - #1299
- [x] get_format more formats - #1343
- [x] last_day - #1344
- [x] localtime - #754
- [x] localtimestamp - #754
- [x] minute_of_day - #1207
- [x] minute_of_hour - #1230
- [x] month_of_year - #1129
- [x] now - #754
- [x] period_add - #933
- [x] period_diff - #933
- [x] sec_to_time - #1378
- [x] second_of_minute - #1231
- [x] str_to_date - #1420
- [x] subdate (update) - #1182
- [x] subtime - #1194
- [x] sysdate - #754
- [x] time - #991
- [x] timediff/time_diff - #1195
- [x] timestamp - #1254
- [x] timestampadd - #1451
- [x] timestampdiff - #1467
- [x] time_format - #1301
- [x] to_seconds - #1419
- [x] unix_timestamp - #835
- [x] utc_date - #1193
- [x] utc_time - #1193
- [x] utc_timestamp - #1193
- [x] weekday - #1418
- [x] weekofyear - #1345
- [x] week_of_year - #1127
- [x] yearweek - #1417
- [x] `>=`/`>`/`=`/`!=`/`<`/`<=` (comparison operators for datetime types) - #1196
- [x] `min`/`max`/`avg` aggregations on datetime types - #1061
- [ ] #1436

Further improvements:
- [ ] #859 
- [x] #861
- [ ] #862
- [ ] #853 (#1328)
- [ ] #852 
- [ ] #855
- [ ] #794/#126

**Comment by GabeFernandez310** [comment]
Date_format may need to be fixed to deprecate legacy. There are legacy tests which fail in the new engine if legacy is disabled (possibly due to the lack of support for a 3rd argument for a timezone).

These include the following in `DateFormatIT`:
- DateFormatIT. and
- DateFormatIT. equalTo
- DateFormatIT. greaterThan
- DateFormatIT. greaterThanOrEqualTo
- DateFormatIT. lessThan
- DateFormatIT. lessThanOrEqualTo
- DateFormatIT. or
- DateFormatIT. sortByDateFormat

**Comment by Yury-Fridlyand** [comment]
Closed as completed.
