### ISSUE TITLE
[FEATURE] Support Cross Cluster Search in SQL/PPL

### ISSUE THREAD

**Issue by penghuo** [opensearch-project/sql#789]
**Is your feature request related to a problem?**
Currently, SQL/PPL does not support cross cluster search (CCS) because CCS does not support fetch index mapping from remote cluster

**What solution would you like?**
Support CCS in SQL/PPL

**Comment by padmashreemutha** [comment]
Yes, I would like to have this feature to get the CCS capability with my old SQL queries.

**Comment by seankao-az** [comment]
# 1 Introduction

We will allow any node in an opensearch cluster to execute search requests against other opensearch clusters using PPL and SQL.

# 2 Background

## 2.1 Cross Cluster Search (CCS) in OpenSearch

OpenSearch supports cross cluster search using the following syntax:

```
# Search index_1 on remote cluster cluster_1
GET cluster_1:index_1/_search

# Search index_1 on both the local cluster and remote cluster cluster_1
GET index_1,cluster_1:index_1/_search

# Search index_1 on both the remote clusters cluster_1 and cluster_2
GET cluster_1:index_1,cluster_2:index_1/_search

# Search index that matches the name pattern on remote cluster cluster_1
GET cluster_1:index_*/_search

# Search all indices on all remote clusters; local cluster NOT included
GET *:*/_search
```

## 2.2 SQL Search

SQL syntax for querying multiple indices isn’t using the comma syntax. We can use the `UNION` keyword.

```sql
-- This is NOT supported
SELECT * FROM index_1,index_2

-- This is supported
SELECT * FROM index_1
UNION
SELECT * FROM index_2
```

Using the asterisk character (*), we can still query multiple indices that match the expression. However, we do not support searching only using an asterisk.

```sql
-- This is supported
SELECT * FROM index_*

-- This is NOT supported
SELECT * FROM *
```

## 2.3 PPL Search

Both asterisk in index names and comma-separated multi-index search are supported. However, we do not wupport searching only using an asterisk.

```
# These are supported
search source=index_*
search source=index_1,index_2

# This is NOT supported
search source=*
```

# 3 User Interface (RFC)

## 3.1 Query Option 1: Colon syntax

This option uses the same identifier syntax as that of CCS in OpenSearch.

### 3.1.1 Identifiers

Identifiers should match one of the following syntax:

* `<index-identifier>` for local cluster query
* `<cluster-identifier>:<index-identifier>` for remote cluster query

Both `<index-identifier>` and `<cluster-identifier>` can contain asterisks (*) for pattern matching.

### 3.1.2 Examples

#### PPL

```
search source=cluster_1:index_1
search source=index_1,cluster_1:index_1,cluster_2:index_1
```

#### SQL

```sql
SELECT * FROM cluster_1:index_1
SELECT * FROM index_1 UNION SELECT * FROM cluster_1:index_1
```

### 3.1.3 Pros and Cons

#### Pros

* Match the user experience with OpenSearch query, which also uses the `<cluster>:<index>` syntax
* No ambiguity in resolving names, as index identifiers must not contain colons (:)
* Could forward resolving logic of cluster name expression to OpenSearch, as it’s a syntax that OpenSearch recognizes

#### Cons

* RFC

## 3.2 Query Option 2: Dot syntax

This option provides the same user experience with [federated query engine with datasources](https://github.com/opensearch-project/sql/blob/main/docs/user/ppl/admin/datasources.rst). In short, with datasources, users can provide the name and connector for an external datasource, and use the following PPL search to refer an entity from the datasource as a table:

```
# the entity as a table is provided by the abstraction designed by the connector
search source=<datasource-name>.<entity> | <piped-commands>
```

The goal of this option is to encapsulate cross clusters as datasources using the same notion.

### 3.2.1 Identifiers

Identifiers should match one of the following syntax:

* `<index-identifier>` for local cluster query
* `<cluster-identifier>.<index-identifier>` for remote cluster query

Both `<index-identifier>` and `<cluster-identifier>` can contain asterisks (*) for pattern matching.

### 3.2.2 Examples

#### PPL

```
search source=cluster_1.index_1
search source=index_1,cluster_1.index_1,cluster_2.index_1
```

#### SQL

```sql
SELECT * FROM cluster_1.index_1
SELECT * FROM index_1 UNION SELECT * FROM cluster_1.index_1
```

### 3.2.3 Pros and Cons

#### Pros

* Provide a unified query user experience with datasources

#### Cons

* Ambiguity in resolving name expressions, as index identifiers could contain dots (.)
* No support for multi-indices syntax in PPL
    * `search source=index_1,cluster_1.index_1` this syntax isn’t a normal use case for federated query
* Need extra work for cluster name expression matching when it contains asterisks (*), as this also diverges from the federated query use case

## 3.3 Pure wildcard matching (RFC)

Do we want to support this: `search source=*:*` (only an asterisk for identifier expression)?
Or is `search source=c*:i*` (asterisk + any other character) good enough?

## 3.4 Response formats

Response formats are exactly the same as a regular local cluster search. They are described here: https://opensearch.org/docs/latest/search-plugins/sql/response-formats/

# 4 Limitations (RFC)

We impose the following limitations for PPL/SQL cross cluster search:

* All indices in a query should have the same index mappings (schemas)
* The index mappings (schemas) should be present on the local cluster

The concrete rules are subject to change, but the idea is that we should be able to find the mapping locally for at least one index:

```
# Use index mapping of index_1 at local cluster 
search source=cluster_1:index_1

# Use index mapping of index_1 at local cluster
search source=index_1,cluster_1:index_1

# Use index mapping of index_1 at local cluster
# Both indices are assumed to have the same index mapping
search source=cluster_2:index_2,index_1

# Use index mapping of index_1 or index_2 at local cluster
# Both indices are assumed to have the same index mapping
search source=cluster_1:index_1,cluster_2:index_2
```

## Reasoning

We impose these limitations because currently, OpenSearch does not support cross cluster query for index mapping, which the jdbc response format requires.

The most common use case for this CCS feature is to search for data across multiple cluster shards. Within a single search query, it’s reasonable to assume that the schema is the same across all indices, so that the query response makes sense, and it’s easier for post-processing.

If either of the limitation is violated, we might either

* attempt to union the index mappings of multiple indices. This is our current approach for local cluster search when multiple indices are queried. When there is conflict in a field, we pick one arbitrarily.
* throw an error

## Caveat

One thing to note is that if the user wants to search only a single index on a single remote cluster, and that the same index name doesn’t also exist on the local cluster, we do not allow such search. A workaround for this is that the user create a mapping table for that index on the local cluster. It does not need to be an index that stores data. It contains only the schema. This way, we could search the data on the remote cluster, and combine it with the schema stored at the local cluster, to make a query response.

## Remove Limitation
We could remove such restrictions once cross cluster index mapping query is supported in OpenSearch core.

**Comment by anirudha** [comment]
Remote cluster shouldn't be data sources. Today's concepts of cross cluster exists independent of data sources

**Comment by anirudha** [comment]
I would prioritize PPL work over sql. It's would be always good to have both/ but we have many users asking for ppl soon.

**Comment by seankao-az** [comment]
## Tasks

* [ ] Development
    * [ ] modify grammar for ppl
    * [ ] search field mapping at local cluster
* [ ] Testing
    * [ ] unit test (full coverage)
    * [ ] integration test (need cross cluster setup)
    * [ ] piped commands should work with ccs
    * [ ] security plugin and cross cluster credentials
* [ ] Communication to customer about feature, and more importantly, the restriction
    * [ ] build a dev version to share with customer
    * [ ] documentation in project
    * [ ] documentation on OpenSearch website
